version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Engine
          command: |
            docker run \
            --name dagger-engine \
            --privileged \
            --stop-signal SIGTERM \
            -d \
            -e _EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN=$CACHE_TOKEN \
            -e _EXPERIMENTAL_DAGGER_CACHESERVICE_URL=https://api.dagger.cloud/magicache \
            -v dagger-engine:/var/lib/dagger \
            registry.dagger.io/engine:v0.6.2
      - run:
          name: Dagger Test Pipeline
          command: go run ./ci ci
      - run:
          command: docker stop --time 60 dagger-engine
      - run:
          command: docker logs dagger-engine
workflows:
  test:
    jobs:
      - test
