name: develop
on:
  issues:
    types:
      - labeled
jobs:
  develop:
    if: github.event.label.name == 'develop'
    name: develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.7
      - name: Check
        run: dagger call develop-pull-request --github-token GH_TOKEN --issue-id ${{ github.event.issue.number }} --model gemini-2.0-flash
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.AGENT_PAT }}
