name: PR Slash Commands
on:
  issue_comment:
    types: [created]
jobs:
  comment-created:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
      - name: PR Feedback
        if: contains(github.event.comment.body, '/agent')
        run: dagger call pull-request-feedback --github-token GH_TOKEN --issue-id ${{ github.event.issue.number }} --feedback "${{ github.event.comment.body }}"
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.AGENT_PAT }}
      - name: PR Review
        if: contains(github.event.comment.body, '/review')
        run: dagger call pull-request-review --github-token GH_TOKEN --issue-id ${{ github.event.issue.number }}
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
