name: release
on:
  push:
    tags:
      - "**"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dagger
        uses: dagger/dagger-for-github@v5
        with:
          args: all --source . --release --tag $GITHUB_REF_NAME --infisical-token ${{ secrets.INFISICAL_TOKEN }} --infisical-project 6545b34313c9b9239b0f7183
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
