name: ci
on:
  push:
    branches: ["**"]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dagger
        uses: dagger/dagger-for-github@v7
        with:
          args: all --source .
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
