name: ci
on:
  push:
    branches: ["**"]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Dagger
        uses: kpenfound/dagger-action@main
        with:
          args: all --source https://github.com/kpenfound/greetings-api\#${GITHUB_REF_NAME}
          module: github.com/kpenfound/greetings-api
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
